#!/bin/bash

set -e

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          Hyprland Customizations - Omarchy Approach            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Following omarchy best practices, all Hyprland customizations"
echo "are now integrated directly into the appropriate config files:"
echo ""
echo "  📁 ~/.config/hypr/bindings.conf"
echo "     - Custom browser (Chromium with 0.8 scaling)"
echo "     - App shortcuts (Discord, Notion)"
echo "     - Vim-style navigation (h/j/k/l)"
echo "     - Monitor switching (period/comma)"
echo "     - Lid switch handling"
echo ""
echo "  📁 ~/.config/hypr/monitors.conf"
echo "     - Monitor scaling (2.0)"
echo ""
echo "  📁 ~/.config/hypr/input.conf"
echo "     - Caps Lock as Ctrl"
echo "     - Keyboard repeat settings"
echo "     - Touchpad scroll factor"
echo ""
echo "  📁 ~/.config/hypr/looknfeel.conf"
echo "     - Window gaps (0)"
echo "     - DPMS settings"
echo ""
echo "✅ All customizations are in ~/.config/ and will persist through"
echo "   omarchy updates."
echo ""
echo "💡 To modify settings:"
echo "   - Edit the files above directly"
echo "   - Use: hyprctl reload (to apply changes)"
echo ""
echo "📝 The old hyprland-overrides.conf has been archived for reference"
echo ""
